# Generated by Django 3.1.5 on 2021-01-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RotFrontprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotfrontprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
